### ISSUE TITLE
Why so many dependencies?

### ISSUE THREAD

**Issue by mgroeneweg** [datalogic/react-native-datalogic-module#1]
Hi,

I really like the library, works great and quick to implement.

However, packaging it is something completely different. Why does it have so many dependencies? Is there any chance some may actually be devdependencies? I end up with over 29.000 objects in 850 packages after adding the library.

Thanks in advance.

**Comment by mgroeneweg** [comment]
To follow up on this, I created a fork in which I removed all prod dependencies. Our usecase runs just fine and builds a lot faster too.

Please cleanup the dependencies.

**Comment by codybrookshear** [comment]
Hi @mgroeneweg,

I suspect you are correct, that there is no good reason for us to have so many dependencies. I will put this request in our internal tracker and eliminate all possible dependencies. I'll post an update here when complete.

Thanks for your feedback,
Cody

**Comment by mgroeneweg** [comment]
Hi @codybrookshear,

Thanks! I will update our app as soon as the update is available.

With regards,

Marcel

**Comment by mgroeneweg** [comment]
Hi @codybrookshear Any news on this?

**Comment by jonahgeorge** [comment]
Here's the result of running [`npx depcheck`](https://www.npmjs.com/package/depcheck) on the repo: [depcheck.log](https://github.com/datalogic/react-native-datalogic-module/files/7980572/depcheck.log)

**Comment by mgroeneweg** [comment]
Indeed! I use a fork in which I cleared the dependencies in package.json. Only the devDependencies and it works just fine.

**Comment by jmmcconnell** [comment]
@mgroeneweg Given our current priorities, this will likely address late in the year.

**Comment by mgroeneweg** [comment]
Pity. It is such a small change. Late this year could mean the issue is left dangling for a year. That does not look good for our customers who buy your scanners!

**Comment by sethjray** [comment]
Removed unused dependencies with latest overhaul update

**Comment by mgroeneweg** [comment]
Great! I will ask the team to ask the new version with their scanners.
